server:
  port: 8090
  servlet:
    context-path: /
  tomcat:
    max-http-form-post-size: 200MB
spring:
  application:
    name: server1
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.url:127.0.0.1}:${nacos.port:8848}
        username: ${nacos.name:nacos}
        password: ${nacos.password:nacos}
        namespace: ${nacos.namespace:explore}
      config:
        server-addr: ${nacos.url:127.0.0.1}:${nacos.port:8848}
        username: ${nacos.name:nacos}
        password: ${nacos.password:nacos}
        file-extension: yml
        namespace: ${nacos.namespace:explore}
        shared-configs: explorer-server1.yml
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
ilzf:
  swagger:
    group-name: server1
    package-path: com.ilzf.server1.controller