server:
  port: 8086
  servlet:
    context-path: /
  tomcat:
    max-http-form-post-size: 200MB
spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
ilzf:
  swagger:
    group-name: 单元测试junit
    package-path: com.ilzf.testjunit.controller