server:
  port: 8098
  servlet:
    context-path: /
  tomcat:
    max-http-form-post-size: 200MB
spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
ilzf:
  swagger:
    group-name: 测试mybatis
    package-path: com.ilzf.mybatis.controller

##    driver-class-name: org.sqlite.JDBC
##      url: jdbc:sqlite:D:\\eclipse-workspace\v2-goview-bate\sqllite\goview.db
      #linux服务器
      #url: jdbc:sqlite://home/cqfy/project/OSSDATABASE/oss.db
##      username:
##      password: