server:
  port: 8081
  servlet:
    context-path: /
  tomcat:
    max-http-form-post-size: 200MB
spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
ilzf:
  swagger:
    group-name: 测试aop
    package-path: com.ilzf.aspect.controller