server:
  port: 8093
spring:
  #  main:
  #    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      #          lower-case-service-id: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowedOriginPatterns: "*"
            allowed-headers: "*"
            allowed-methods: "*"
            maxAge: 360000
            exposedHeaders: "Content-Disposition,Content-Type,Cache-Control"